import { useEffect, useState } from "react";
import { fetchContent } from "@/lib/contentApi";

/* Single source of truth for editable site copy.
   Each field maps to a site_content key. The public pages read these (falling
   back to `default`), and the admin Pages editor renders + persists them.
   A field with `kind: "video"` renders a URL input + upload/replace action.
   Word-by-word "statement" lines (split-words) keep their scroll animation by
   rendering the in-code markup until the field is edited (see usePageText). */
export const PAGE_CONTENT = [
  {
    title: "Home", path: "/",
    sections: [
      { name: "Hero", fields: [
        { key: "home.hero.proof", label: "Proof line", default: "★★★★★ 5.0 — 1,800+ success stories" },
        { key: "home.hero.title", label: "Headline", default: "Brands built to empower growth" },
        { key: "home.hero.sub", label: "Subheadline", textarea: true, default: "Offering tailored creative solutions and brand packages designed to amplify your business — efficient, impactful, and built for growth." },
        { key: "home.hero.btn_primary", label: "Primary button", half: true, default: "Get a Quote" },
        { key: "home.hero.btn_secondary", label: "Secondary button", half: true, default: "Real Results" },
        { key: "home.hero.booking", label: "Booking box heading", default: "Book your free design consultation" },
        { key: "home.hero.note", label: "Marker note (handwritten)", half: true, default: "it's free — grab a slot!" },
      ]},
      { name: "Top marquee", fields: [
        { key: "home.marquee1.items", label: "Marquee phrases (comma separated)", textarea: true, default: "Logo Design, Vehicle Wraps, Websites, Business Cards, Packaging & Labels, Company Shirts, Brochures, Menus" },
      ]},
      { name: "Who we are", fields: [
        { key: "home.about.eyebrow", label: "Eyebrow", default: "Who we are" },
        { key: "home.about.statement", label: "Statement", textarea: true, default: "We solve brand challenges through distinctive design — from bold logos to eye-catching vehicle wraps, strategic websites and more." },
        { key: "home.about.copy", label: "Body copy", textarea: true, rows: 4, default: "je.design — Jeremy Ellsworth Designs LLC — is a full-service design agency with a specialty in home service brands: HVAC, electrical, plumbing, roofing, painting and beyond. What started as one designer's craft 20 years ago is now a 10-person team of designers, project managers and brand consultants — every concept researched, brainstormed and designed entirely in-house." },
        { key: "home.about.cta_primary", label: "Primary button", half: true, default: "Work with us" },
        { key: "home.about.cta_secondary", label: "Secondary button", half: true, default: "Meet the team" },
        { key: "home.about.stat1_value", label: "Stat 1 — number", half: true, default: "20" },
        { key: "home.about.stat1_label", label: "Stat 1 — label", half: true, default: "Years of experience" },
        { key: "home.about.stat2_value", label: "Stat 2 — number", half: true, default: "10" },
        { key: "home.about.stat2_label", label: "Stat 2 — label", half: true, default: "In-house creatives" },
        { key: "home.about.stat3_value", label: "Stat 3 — number", half: true, default: "1800" },
        { key: "home.about.stat3_label", label: "Stat 3 — label", half: true, default: "Five-star reviews" },
        { key: "home.about.stat4_value", label: "Stat 4 — number", half: true, default: "8000" },
        { key: "home.about.stat4_label", label: "Stat 4 — label", half: true, default: "Startups served, US-wide" },
      ]},
      { name: "Work", fields: [
        { key: "home.work.eyebrow", label: "Eyebrow", default: "Selected work" },
        { key: "home.work.title", label: "Section title", default: "Brand projects" },
        { key: "home.work.sub", label: "Subtitle", textarea: true, default: "Strategic brand transformations that tell powerful stories and create lasting connections with your audience." },
        { key: "home.work.foot", label: "Foot line", textarea: true, default: "Our work in action — bold design, bringing visionary ideas to life through strategic creativity." },
        { key: "home.work.foot_btn", label: "Foot button", default: "Start your project" },
      ]},
      { name: "Mascot divider marquee", fields: [
        { key: "home.marquee2.items", label: "Marquee phrases (comma separated)", textarea: true, default: "Mascot Logos, Impossible to Ignore, Full of Personality, Brands They Remember" },
      ]},
      { name: "Mascots", fields: [
        { key: "home.mascots.eyebrow", label: "Eyebrow", default: "Mascot logos" },
        { key: "home.mascots.title", label: "Section title", default: "Mascots they remember" },
        { key: "home.mascots.sub", label: "Subtitle", textarea: true, default: "Mascot logos make your brand impossible to ignore — full of personality, character, and the kind of fun that customers remember." },
        { key: "home.mascots.uses_label", label: "Uses label", default: "One mascot, every use case" },
        { key: "home.mascots.chips", label: "Use-case chips (comma separated)", textarea: true, default: "Primary lockup, Mascot-only mark, Badge, Roundel, Wordmark, Truck wraps, Apparel, Yard signs, Socials & stickers" },
        { key: "home.mascots.btn", label: "Button", default: "Get a mascot" },
      ]},
      { name: "Services", fields: [
        { key: "home.services.eyebrow", label: "Eyebrow", default: "What we do" },
        { key: "home.services.title", label: "Section title", default: "Creative solutions" },
        { key: "home.services.sub", label: "Subtitle", textarea: true, default: "We solve brand challenges through distinctive design — every deliverable handled in-house by a dedicated 10-person creative team." },
        { key: "home.services.s1_name", label: "Service 1 — name", half: true, default: "Logo & Branding" },
        { key: "home.services.s1_desc", label: "Service 1 — description", half: true, default: "Logo + five-page style guide" },
        { key: "home.services.s2_name", label: "Service 2 — name", half: true, default: "Vehicle Wrap" },
        { key: "home.services.s2_desc", label: "Service 2 — description", half: true, default: "Designs that turn heads on every road" },
        { key: "home.services.s3_name", label: "Service 3 — name", half: true, default: "Website Design & Dev." },
        { key: "home.services.s3_desc", label: "Service 3 — description", half: true, default: "Strategic websites built to convert" },
        { key: "home.services.s4_name", label: "Service 4 — name", half: true, default: "Print Collateral" },
        { key: "home.services.s4_desc", label: "Service 4 — description", half: true, default: "Business cards · Brochures · Menus" },
        { key: "home.services.s5_name", label: "Service 5 — name", half: true, default: "Packaging & Labels" },
        { key: "home.services.s5_desc", label: "Service 5 — description", half: true, default: "Shelf-ready product design" },
        { key: "home.services.s6_name", label: "Service 6 — name", half: true, default: "Company Apparel" },
        { key: "home.services.s6_desc", label: "Service 6 — description", half: true, default: "Shirts and uniforms your crew will wear proudly" },
      ]},
      { name: "Process", fields: [
        { key: "home.process.eyebrow", label: "Eyebrow", default: "The process" },
        { key: "home.process.title", label: "Section title", default: "How we work" },
        { key: "home.process.sub", label: "Subtitle", textarea: true, default: "A proven sprint that takes you from first call to launch-ready brand — most projects delivered in 2–3 weeks, not months." },
        { key: "home.process.p1_title", label: "Step 1 — title", half: true, default: "Discovery & strategy" },
        { key: "home.process.p1_meta", label: "Step 1 — meta", half: true, default: "Free consultation" },
        { key: "home.process.p1_text", label: "Step 1 — text", textarea: true, default: "Every project starts with a thorough discovery phase — clarifying your vision, objectives and preferences so every concept aligns with your goals." },
        { key: "home.process.p2_title", label: "Step 2 — title", half: true, default: "Original concepts" },
        { key: "home.process.p2_meta", label: "Step 2 — meta", half: true, default: "First draft in 5–7 business days" },
        { key: "home.process.p2_text", label: "Step 2 — text", textarea: true, default: "Fresh, 100% original concepts — researched, brainstormed and designed in-house by real designers. No AI, no templates, no recycled elements — ever." },
        { key: "home.process.p3_title", label: "Step 3 — title", half: true, default: "Refine together" },
        { key: "home.process.p3_meta", label: "Step 3 — meta", half: true, default: "Typically 5–7 revisions" },
        { key: "home.process.p3_text", label: "Step 3 — text", textarea: true, default: "You get a private communication channel and a dedicated creative team. If something isn't sitting right, we address it before moving forward." },
        { key: "home.process.p4_title", label: "Step 4 — title", half: true, default: "Launch & deliver" },
        { key: "home.process.p4_meta", label: "Step 4 — meta", half: true, default: "Most projects in 2–3 weeks" },
        { key: "home.process.p4_text", label: "Step 4 — text", textarea: true, default: "Final files in AI, SVG, PDF, JPG and PNG — print-crisp, web-ready and yours to own forever. Then we help you roll it out everywhere." },
      ]},
      { name: "Videos", fields: [
        { key: "home.videos.eyebrow", label: "Eyebrow", default: "Watch the craft" },
        { key: "home.videos.title", label: "Section title", default: "Sketch to sizzle" },
        { key: "home.videos.sub", label: "Subtitle", textarea: true, default: "Watch as we transform brands through bold design, bringing visionary ideas to life through strategic creativity." },
        { key: "home.videos.v1_title", label: "Video 1 — title", half: true, default: "Pōlani Poised" },
        { key: "home.videos.v1_sub", label: "Video 1 — subtitle", half: true, default: "Vector logo timelapse" },
        { key: "home.videos.v1_url", label: "Video 1 — YouTube link or upload", kind: "video", default: "https://www.youtube.com/watch?v=-BNnw0WfyjM" },
        { key: "home.videos.v2_title", label: "Video 2 — title", half: true, default: "Igniting Creativity. Fueling Brands." },
        { key: "home.videos.v2_sub", label: "Video 2 — subtitle", half: true, default: "Brand reel" },
        { key: "home.videos.v2_url", label: "Video 2 — YouTube link or upload", kind: "video", default: "https://www.youtube.com/watch?v=BpuC_iyq0l8" },
        { key: "home.videos.v3_title", label: "Video 3 — title", half: true, default: "Computer Wiz" },
        { key: "home.videos.v3_sub", label: "Video 3 — subtitle", half: true, default: "Sketch logo timelapse" },
        { key: "home.videos.v3_url", label: "Video 3 — YouTube link or upload", kind: "video", default: "https://www.youtube.com/watch?v=P-Zq6cjDuuE" },
        { key: "home.videos.v4_title", label: "Video 4 — title", half: true, default: "Suegra's Pika-Pika — logo journey" },
        { key: "home.videos.v4_sub", label: "Video 4 — subtitle", half: true, default: "Sketch to sizzle" },
        { key: "home.videos.v4_url", label: "Video 4 — YouTube link or upload", kind: "video", default: "https://www.youtube.com/watch?v=PXyjsFFNHAs" },
        { key: "home.videos.v5_title", label: "Video 5 — title", half: true, default: "Boss Hogg BBQ" },
        { key: "home.videos.v5_sub", label: "Video 5 — subtitle", half: true, default: "Vector logo timelapse" },
        { key: "home.videos.v5_url", label: "Video 5 — YouTube link or upload", kind: "video", default: "https://www.youtube.com/watch?v=3IjRK4f669A" },
        { key: "home.videos.v6_title", label: "Video 6 — title", half: true, default: "FP Outfitters" },
        { key: "home.videos.v6_sub", label: "Video 6 — subtitle", half: true, default: "Sketch logo timelapse" },
        { key: "home.videos.v6_url", label: "Video 6 — YouTube link or upload", kind: "video", default: "https://www.youtube.com/watch?v=0_NqkhfwIHI" },
        { key: "home.videos.foot", label: "Foot line", textarea: true, default: "New timelapses, process breakdowns and brand launches — every week." },
        { key: "home.videos.foot_btn", label: "Foot button", half: true, default: "More on YouTube" },
        { key: "home.videos.foot_href", label: "Foot button link", half: true, default: "https://www.youtube.com/@jeremyellsworthdesignsllc" },
      ]},
      { name: "Why brands pick us", fields: [
        { key: "home.why.eyebrow", label: "Eyebrow", default: "The difference" },
        { key: "home.why.title", label: "Section title", default: "Why brands pick us" },
        { key: "home.why.note", label: "Subtitle", textarea: true, default: "Big-agency output without the big-agency bloat — faster, flatter and more personal than the corporate branding shops." },
        { key: "home.why.l1_big", label: "Line 1 — heading", half: true, default: "Real humans, real answers." },
        { key: "home.why.l1_small", label: "Line 1 — detail", textarea: true, default: "A trained, dedicated creative team in a private channel — not a ticket queue. From kickoff to launch." },
        { key: "home.why.l2_big", label: "Line 2 — heading", half: true, default: "Flat pricing, no surprises." },
        { key: "home.why.l2_small", label: "Line 2 — detail", textarea: true, default: "You know the full investment before we start — no hidden fees, no change orders." },
        { key: "home.why.l3_big", label: "Line 3 — heading", half: true, default: "Days, not months." },
        { key: "home.why.l3_small", label: "Line 3 — detail", textarea: true, default: "First concepts in 5–7 business days. Most brands launch in 2–3 weeks." },
        { key: "home.why.l4_big", label: "Line 4 — heading", half: true, default: "Drawn by hand, never AI." },
        { key: "home.why.l4_small", label: "Line 4 — detail", textarea: true, default: "Every concept starts from a blank page with real designers — no AI-generated artwork, no templates, no recycled elements. Ever." },
        { key: "home.why.l4_link", label: "Line 4 — link label", half: true, default: "Watch us draw ↗" },
        { key: "home.why.l4_href", label: "Line 4 — link URL", half: true, default: "https://www.youtube.com/@jeremyellsworthdesignsllc" },
        { key: "home.why.l5_big", label: "Line 5 — heading", half: true, default: "Your brand, your files." },
        { key: "home.why.l5_small", label: "Line 5 — detail", textarea: true, default: "AI, SVG, PDF, JPG and PNG with every project — yours to own forever." },
      ]},
      { name: "Results", fields: [
        { key: "home.results.eyebrow", label: "Eyebrow", default: "Real results" },
        { key: "home.results.title", label: "Section title", default: "Rebrands that pay for themselves" },
        { key: "home.results.sub", label: "Subtitle", textarea: true, default: "Real customers, real growth — revenue increases reported by owners after rebranding with Jeremy Ellsworth Designs LLC." },
        { key: "home.results.foot", label: "Foot line", default: "Your rebrand could be next on this wall." },
        { key: "home.results.foot_btn", label: "Foot button", default: "Start yours" },
      ]},
      { name: "Brand Access Program", fields: [
        { key: "home.bap.eyebrow", label: "Eyebrow", default: "A better way to pay" },
        { key: "home.bap.title", label: "Section title", default: "Brand Access Program" },
        { key: "home.bap.sub", label: "Subtitle", textarea: true, default: "Get branded now and pay as you grow — $150 down, then $150 a month until paid off. Your capital stays in your business, your files are yours from day one." },
        { key: "home.bap.f1_title", label: "Feature 1 — title", half: true, default: "Full file access from day one" },
        { key: "home.bap.f1_sub", label: "Feature 1 — detail", half: true, default: "No holding assets hostage — ever" },
        { key: "home.bap.f2_title", label: "Feature 2 — title", half: true, default: "Work starts immediately" },
        { key: "home.bap.f2_sub", label: "Feature 2 — detail", half: true, default: "No waiting for approval rounds" },
        { key: "home.bap.f3_title", label: "Feature 3 — title", half: true, default: "Logo + variations, every format" },
        { key: "home.bap.f3_sub", label: "Feature 3 — detail", half: true, default: "AI · SVG · PNG · PDF · EPS" },
        { key: "home.bap.f4_title", label: "Feature 4 — title", half: true, default: "Brand colors, type & guidelines" },
        { key: "home.bap.f4_sub", label: "Feature 4 — detail", half: true, default: "A complete system, documented" },
        { key: "home.bap.f5_title", label: "Feature 5 — title", half: true, default: "Revision rounds included" },
        { key: "home.bap.f5_sub", label: "Feature 5 — detail", half: true, default: "No extra fees, no scope creep" },
        { key: "home.bap.f6_title", label: "Feature 6 — title", default: "Cancel anytime after completion" },
        { key: "home.bap.price", label: "Price (today)", half: true, default: "150" },
        { key: "home.bap.price_label", label: "Price label", half: true, default: "down today — work starts immediately" },
        { key: "home.bap.then_label", label: "\"Then\" label", half: true, default: "then" },
        { key: "home.bap.month_amount", label: "Monthly amount", half: true, default: "$150" },
        { key: "home.bap.month_label", label: "Monthly label", default: "/mo until paid off" },
        { key: "home.bap.btn_primary", label: "Primary button", half: true, default: "Get Instant Quote" },
        { key: "home.bap.btn_primary_href", label: "Primary button link", half: true, default: "https://agreement.je.design/brand-access-program" },
        { key: "home.bap.btn_secondary", label: "Secondary link", default: "Learn how the program works →" },
        { key: "home.bap.fineprint", label: "Fine print", default: "No hidden fees · no hostage files · cancel anytime after completion." },
      ]},
      { name: "Reviews", note: { text: "The scrolling review cards are pulled live from the Reviews workspace — add, edit or feature reviews there. Only the section heading and footer below are editable here.", link: "/admin/reviews", linkLabel: "Open Reviews →" }, fields: [
        { key: "home.reviews.eyebrow", label: "Eyebrow", default: "Reviews" },
        { key: "home.reviews.title", label: "Section title", default: "1.8k success stories" },
        { key: "home.reviews.sub", label: "Subtitle", textarea: true, default: "At je.design, we are committed to your success. We believe that our success lies in your success — and we are dedicated to helping you achieve it." },
        { key: "home.reviews.rating", label: "Footer rating line", default: "5.0 ★ on Google & Facebook" },
        { key: "home.reviews.foot_btn", label: "Footer button", default: "Start your story" },
      ]},
      { name: "Team", fields: [
        { key: "home.team.eyebrow", label: "Eyebrow", default: "The people" },
        { key: "home.team.title", label: "Section title", default: "Team je.design" },
        { key: "home.team.sub", label: "Subtitle", textarea: true, default: "Your five-star creative design agency — 10 strategists, designers and brand consultants behind every brand we build." },
        { key: "home.team.m1_name", label: "Member 1 — name", half: true, default: "Jeremy E." },
        { key: "home.team.m1_role", label: "Member 1 — role", half: true, default: "Owner / Designer" },
        { key: "home.team.m1_photo", label: "Member 1 — photo", kind: "image", default: "/assets/img/team/jeremy.jpg" },
        { key: "home.team.m2_name", label: "Member 2 — name", half: true, default: "Paul F." },
        { key: "home.team.m2_role", label: "Member 2 — role", half: true, default: "Creative Director" },
        { key: "home.team.m2_photo", label: "Member 2 — photo", kind: "image", default: "" },
        { key: "home.team.m3_name", label: "Member 3 — name", half: true, default: "Robin D." },
        { key: "home.team.m3_role", label: "Member 3 — role", half: true, default: "VP of Operations" },
        { key: "home.team.m3_photo", label: "Member 3 — photo", kind: "image", default: "/assets/img/team/robin.jpg" },
        { key: "home.team.m4_name", label: "Member 4 — name", half: true, default: "Roy Marc C." },
        { key: "home.team.m4_role", label: "Member 4 — role", half: true, default: "Ads Manager" },
        { key: "home.team.m4_photo", label: "Member 4 — photo", kind: "image", default: "/assets/img/team/roymarc.jpg" },
        { key: "home.team.m5_name", label: "Member 5 — name", half: true, default: "Charlie P." },
        { key: "home.team.m5_role", label: "Member 5 — role", half: true, default: "Human Resource" },
        { key: "home.team.m5_photo", label: "Member 5 — photo", kind: "image", default: "/assets/img/team/charlie.jpg" },
        { key: "home.team.m6_name", label: "Member 6 — name", half: true, default: "Robert A." },
        { key: "home.team.m6_role", label: "Member 6 — role", half: true, default: "Design Consultant" },
        { key: "home.team.m6_photo", label: "Member 6 — photo", kind: "image", default: "/assets/img/team/roberta.jpg" },
        { key: "home.team.m7_name", label: "Member 7 — name", half: true, default: "Ernst" },
        { key: "home.team.m7_role", label: "Member 7 — role", half: true, default: "Designer" },
        { key: "home.team.m7_photo", label: "Member 7 — photo", kind: "image", default: "/assets/img/team/ernst.jpg" },
        { key: "home.team.m8_name", label: "Member 8 — name", half: true, default: "Robert L." },
        { key: "home.team.m8_role", label: "Member 8 — role", half: true, default: "Designer" },
        { key: "home.team.m8_photo", label: "Member 8 — photo", kind: "image", default: "/assets/img/team/robertl.jpg" },
        { key: "home.team.m9_name", label: "Member 9 — name", half: true, default: "Zyrus T." },
        { key: "home.team.m9_role", label: "Member 9 — role", half: true, default: "Designer" },
        { key: "home.team.m9_photo", label: "Member 9 — photo", kind: "image", default: "/assets/img/team/zyrus.jpg" },
        { key: "home.team.m10_name", label: "Member 10 — name", half: true, default: "Irvan R." },
        { key: "home.team.m10_role", label: "Member 10 — role", half: true, default: "Designer" },
        { key: "home.team.m10_photo", label: "Member 10 — photo", kind: "image", default: "/assets/img/team/irvan.jpg" },
      ]},
      { name: "Contact", fields: [
        { key: "home.contact.marquee", label: "Marquee phrase", default: "Ready to amplify your brand?" },
        { key: "home.contact.bigline", label: "Big line", default: "Let's talk" },
        { key: "home.contact.email", label: "Email address", default: "inquiry@jeremynellsworth.com" },
        { key: "home.contact.para", label: "Paragraph", textarea: true, default: "Tell us about your business and we'll map out the brand package that fits — no surprises, just results." },
      ]},
    ],
  },
  {
    title: "About", path: "/about",
    sections: [
      { name: "Hero", fields: [
        { key: "about.hero.eyebrow", label: "Eyebrow", half: true, default: "Who we are" },
        { key: "about.hero.title", label: "Headline", half: true, default: "The team behind" },
        { key: "about.hero.title_accent", label: "Headline accent", half: true, default: "1,800+ five-stars" },
        { key: "about.hero.sub", label: "Subheadline", textarea: true, default: "A full-service design agency with a specialty in home service brands — built on 20 years of craft, not shortcuts." },
      ]},
      { name: "Story", fields: [
        { key: "about.story.p1", label: "Paragraph 1", textarea: true, rows: 4, default: "je.design — Jeremy Ellsworth Designs LLC — started 20 years ago with one designer and a simple conviction: small businesses deserve brands as professional as the big guys'. Today we're a full bench of designers, project managers and brand consultants serving startups across the United States." },
        { key: "about.story.p2", label: "Paragraph 2", textarea: true, rows: 4, default: "We specialize in home service businesses — HVAC, electrical, plumbing, roofing, painting and beyond — because that's where a bold, memorable brand changes everything: more calls, better jobs, crews that wear the shirt with pride." },
        { key: "about.story.quote", label: "Pull quote", textarea: true, default: "\"We believe that our success lies in your success — and we are dedicated to helping you achieve it.\"" },
        { key: "about.story.quote_cite", label: "Quote attribution", default: "— Jeremy E., Owner / Designer" },
      ]},
      { name: "The people", fields: [
        { key: "about.people.eyebrow", label: "Eyebrow", half: true, default: "The people" },
        { key: "about.people.title", label: "Section title", half: true, default: "Meet the" },
        { key: "about.people.title_accent", label: "Section title accent", half: true, default: "crew" },
        { key: "about.people.sub", label: "Subtitle", textarea: true, default: "Designers, project managers, developers and consultants — every brand gets the whole bench, in a private channel." },
        { key: "home.team.m1_name", label: "Member 1 — name", half: true, default: "Jeremy E." },
        { key: "home.team.m1_role", label: "Member 1 — role", half: true, default: "Owner / Designer" },
        { key: "home.team.m1_photo", label: "Member 1 — photo", kind: "image", default: "/assets/img/team/jeremy.jpg" },
        { key: "home.team.m2_name", label: "Member 2 — name", half: true, default: "Paul F." },
        { key: "home.team.m2_role", label: "Member 2 — role", half: true, default: "Creative Director" },
        { key: "home.team.m2_photo", label: "Member 2 — photo", kind: "image", default: "" },
        { key: "home.team.m3_name", label: "Member 3 — name", half: true, default: "Robin D." },
        { key: "home.team.m3_role", label: "Member 3 — role", half: true, default: "VP of Operations" },
        { key: "home.team.m3_photo", label: "Member 3 — photo", kind: "image", default: "/assets/img/team/robin.jpg" },
        { key: "home.team.m4_name", label: "Member 4 — name", half: true, default: "Roy Marc C." },
        { key: "home.team.m4_role", label: "Member 4 — role", half: true, default: "Ads Manager" },
        { key: "home.team.m4_photo", label: "Member 4 — photo", kind: "image", default: "/assets/img/team/roymarc.jpg" },
        { key: "home.team.m5_name", label: "Member 5 — name", half: true, default: "Charlie P." },
        { key: "home.team.m5_role", label: "Member 5 — role", half: true, default: "Human Resource" },
        { key: "home.team.m5_photo", label: "Member 5 — photo", kind: "image", default: "/assets/img/team/charlie.jpg" },
        { key: "home.team.m6_name", label: "Member 6 — name", half: true, default: "Robert A." },
        { key: "home.team.m6_role", label: "Member 6 — role", half: true, default: "Design Consultant" },
        { key: "home.team.m6_photo", label: "Member 6 — photo", kind: "image", default: "/assets/img/team/roberta.jpg" },
        { key: "home.team.m7_name", label: "Member 7 — name", half: true, default: "Ernst" },
        { key: "home.team.m7_role", label: "Member 7 — role", half: true, default: "Designer" },
        { key: "home.team.m7_photo", label: "Member 7 — photo", kind: "image", default: "/assets/img/team/ernst.jpg" },
        { key: "home.team.m8_name", label: "Member 8 — name", half: true, default: "Robert L." },
        { key: "home.team.m8_role", label: "Member 8 — role", half: true, default: "Designer" },
        { key: "home.team.m8_photo", label: "Member 8 — photo", kind: "image", default: "/assets/img/team/robertl.jpg" },
        { key: "home.team.m9_name", label: "Member 9 — name", half: true, default: "Zyrus T." },
        { key: "home.team.m9_role", label: "Member 9 — role", half: true, default: "Designer" },
        { key: "home.team.m9_photo", label: "Member 9 — photo", kind: "image", default: "/assets/img/team/zyrus.jpg" },
        { key: "home.team.m10_name", label: "Member 10 — name", half: true, default: "Irvan R." },
        { key: "home.team.m10_role", label: "Member 10 — role", half: true, default: "Designer" },
        { key: "home.team.m10_photo", label: "Member 10 — photo", kind: "image", default: "/assets/img/team/irvan.jpg" },
      ]},
    ],
  },
  {
    title: "Work", path: "/work",
    sections: [
      { name: "Hero", fields: [
        { key: "work.hero.eyebrow", label: "Eyebrow", half: true, default: "Selected work" },
        { key: "work.hero.title", label: "Headline", half: true, default: "Brands built to" },
        { key: "work.hero.title_accent", label: "Headline accent", half: true, default: "win their market" },
        { key: "work.hero.sub", label: "Subheadline", textarea: true, default: "Strategic brand transformations that tell powerful stories and create lasting connections with your audience — every one drawn by hand, in-house." },
      ]},
    ],
  },
  {
    title: "Services", path: "/services",
    sections: [
      { name: "Hero", fields: [
        { key: "services.hero.eyebrow", label: "Eyebrow", half: true, default: "What we do" },
        { key: "services.hero.title", label: "Headline", half: true, default: "Creative Brand" },
        { key: "services.hero.title_accent", label: "Headline accent", half: true, default: "solutions" },
        { key: "services.hero.sub", label: "Subheadline", textarea: true, default: "Six ways we make your business impossible to ignore — all under one roof, all by the same hands." },
      ]},
      { name: "Differentiator strip", fields: [
        { key: "services.diff.statement", label: "Statement (large intro line)", textarea: true, rows: 3, default: "Most agencies bury you in process, hand you to account managers and disappear for months. We do the opposite — and it shows in the work." },
        { key: "services.diff.s1_title", label: "Item 1 — title", half: true, default: "All in-house" },
        { key: "services.diff.s1_text", label: "Item 1 — text", textarea: true, default: "One team designs everything you see here. Nothing outsourced, nothing handed off." },
        { key: "services.diff.s2_title", label: "Item 2 — title", half: true, default: "Drawn by hand — never AI" },
        { key: "services.diff.s2_text", label: "Item 2 — text", textarea: true, default: "Every concept starts on a blank page with a real designer. No generated artwork, no templates." },
        { key: "services.diff.s3_title", label: "Item 3 — title", half: true, default: "Flat pricing" },
        { key: "services.diff.s3_text", label: "Item 3 — text", textarea: true, default: "You know the full number before we start. No quote roulette, no change orders." },
        { key: "services.diff.s4_title", label: "Item 4 — title", half: true, default: "Weeks, not months" },
        { key: "services.diff.s4_text", label: "Item 4 — text", textarea: true, default: "First concepts in 5–7 business days. Most projects launch in 2–3 weeks." },
      ]},
      { name: "Program finale", fields: [
        { key: "services.finale.kicker", label: "Kicker", default: "A better way to pay — Brand Access Program" },
        { key: "services.finale.line", label: "Footer line", textarea: true, default: "Full file access from day one, work starts immediately, revisions included — pay it off month by month." },
      ]},
    ],
  },
];

export const CONTENT_DEFAULTS = Object.fromEntries(
  PAGE_CONTENT.flatMap((p) => p.sections.flatMap((s) => s.fields.map((f) => [f.key, f.default])))
);

/* Hook for public pages: returns a `t(key)` reader backed by the content store,
   falling back to the in-code default so the DOM exists before animations init. */
export function usePageText() {
  const [content, setContent] = useState({});
  useEffect(() => {
    let active = true;
    fetchContent().then((c) => { if (active) setContent(c); }).catch(() => {});
    return () => { active = false; };
  }, []);
  const t = (key) => (content[key] ? content[key] : (CONTENT_DEFAULTS[key] ?? ""));
  t.isCustom = (key) => content[key] != null && content[key] !== CONTENT_DEFAULTS[key];
  return t;
}
