// Project data — swap this file for CMS queries later without touching the pages.
export const projects = [
  {
    slug: "boss-hawgs-bbq",
    services: ["brand-identity", "company-apparel"],
    title: "Boss Hawgs BBQ",
    category: "Brand Identity",
    industry: "Food & Beverage",
    cat: "food",
    img: "/assets/img/work/boss-hawgs.jpg",
    blurb: "A bold, mouth-watering identity for a backyard-style BBQ brand — built around a mascot with serious attitude and applied across aprons, signage and packaging.",
    gallery: ["/assets/img/work/boss-hawgs.jpg", "/assets/img/work/stoopid-energy.jpg", "/assets/img/mascots/layer-8.jpg", "/assets/img/mascots/layer-12.jpg", "/assets/img/work/jump-party.jpg", "/assets/img/mascots/layer-7.jpg", "/assets/img/work/macdavy.jpg", "/assets/img/mascots/layer-14.jpg"],
    testimonial: { quote: 'These guys are top notch!! I have had many designers in the past that do not even come close to what these guys put out.', name: "Paul Margott", company: "Window Blasters" },
    deliverables: ["Logo design", "Mascot illustration", "Five-page style guide", "Apparel & collateral"],
    external: "https://je.design/projects/boss-hawgs-bbq-brand-identity",
  },
  {
    slug: "stoopid-energy",
    services: ["brand-identity", "packaging-labels"],
    title: "Stoopid Energy",
    category: "Brand Identity + Product",
    industry: "Food & Beverage",
    cat: "food",
    img: "/assets/img/work/stoopid-energy.jpg",
    blurb: "An energy drink brand that refuses to whisper — identity and can design engineered to jump off the shelf and into the cooler.",
    gallery: ["/assets/img/work/stoopid-energy.jpg", "/assets/img/work/boss-hawgs.jpg", "/assets/img/mascots/layer-8.jpg", "/assets/img/mascots/layer-12.jpg", "/assets/img/work/jump-party.jpg", "/assets/img/mascots/layer-7.jpg", "/assets/img/work/macdavy.jpg", "/assets/img/mascots/layer-14.jpg"],
    testimonial: { quote: 'The results were absolutely incredible! The designs exceeded my expectations in every way.', name: "Shevan Rowland", company: "Lakeview Roofing LLC" },
    deliverables: ["Logo design", "Can & label design", "Five-page style guide", "Launch collateral"],
    external: "https://je.design/projects/stoopid-energy-brand-identity-product-design",
  },
  {
    slug: "high-caliber-electric",
    services: ["brand-identity", "print-collateral"],
    title: "High Caliber Electric",
    category: "Brand Identity",
    industry: "Home Service",
    cat: "home",
    img: "/assets/img/work/high-caliber.jpg",
    blurb: "A sharp, trustworthy identity for an electrical contractor — designed to read instantly on trucks, yard signs and business cards alike.",
    gallery: ["/assets/img/work/high-caliber.jpg", "/assets/img/work/spartan-hvac.jpg", "/assets/img/work/salty-soft-wash.jpg", "/assets/img/work/macdavy.jpg", "/assets/img/revenue/rev-1.jpg", "/assets/img/revenue/rev-5.jpg", "/assets/img/mascots/layer-9.jpg", "/assets/img/mascots/layer-10.jpg"],
    testimonial: { quote: 'Very professional, very quick to respond — and the logo turned out AMAZING!', name: "Ezri Valdes", company: "TrashPanda" },
    deliverables: ["Logo design", "Five-page style guide", "Business cards", "Yard signs"],
    external: "https://je.design/projects/high-caliber-electric-brand-identity",
  },
  {
    slug: "spartan-hvac",
    services: ["brand-identity", "company-apparel"],
    title: "Spartan HVAC",
    category: "Brand Identity",
    industry: "Home Service",
    cat: "home",
    img: "/assets/img/work/spartan-hvac.jpg",
    blurb: "A battle-ready brand for an HVAC crew — a mascot-led identity that makes uniforms feel like armor and trucks impossible to miss.",
    gallery: ["/assets/img/work/spartan-hvac.jpg", "/assets/img/work/high-caliber.jpg", "/assets/img/work/salty-soft-wash.jpg", "/assets/img/work/macdavy.jpg", "/assets/img/revenue/rev-1.jpg", "/assets/img/revenue/rev-5.jpg", "/assets/img/mascots/layer-9.jpg", "/assets/img/mascots/layer-10.jpg"],
    testimonial: { quote: 'Quick turnaround & very professional. I give the team a 10/10.', name: "Julio Santiago", company: "August Hardscapes" },
    deliverables: ["Logo design", "Mascot illustration", "Five-page style guide", "Company apparel"],
    external: "https://je.design/projects/spartan-hvac-brand-identity",
  },
  {
    slug: "salty-soft-wash",
    services: ["brand-identity", "vehicle-wraps"],
    title: "Salty Soft Wash",
    category: "Brand Identity",
    industry: "Home Service",
    cat: "home",
    img: "/assets/img/work/salty-soft-wash.jpg",
    blurb: "A coastal-flavored identity for a pressure washing company — wrapped across the fleet for thousands of daily impressions.",
    gallery: ["/assets/img/work/salty-soft-wash.jpg", "/assets/img/work/high-caliber.jpg", "/assets/img/work/spartan-hvac.jpg", "/assets/img/work/macdavy.jpg", "/assets/img/revenue/rev-1.jpg", "/assets/img/revenue/rev-5.jpg", "/assets/img/mascots/layer-9.jpg", "/assets/img/mascots/layer-10.jpg"],
    testimonial: { quote: 'I could not have asked for a better experience. Working with Jeremy was an insane value!', name: "Nick Boyles", company: "Breeze Painting" },
    deliverables: ["Logo design", "Vehicle wrap design", "Five-page style guide", "Collateral design"],
    external: "https://je.design/projects/salty-soft-wash-brand-identity",
  },
  {
    slug: "macdavy-heating-air",
    services: ["brand-identity", "print-collateral"],
    title: "MacDavy Heating & Air",
    category: "Brand Identity",
    industry: "Home Service",
    cat: "home",
    img: "/assets/img/work/macdavy.jpg",
    blurb: "A friendly, memorable face for a heating and air company — identity and collateral that make a local business feel established.",
    gallery: ["/assets/img/work/macdavy.jpg", "/assets/img/work/high-caliber.jpg", "/assets/img/work/spartan-hvac.jpg", "/assets/img/work/salty-soft-wash.jpg", "/assets/img/revenue/rev-1.jpg", "/assets/img/revenue/rev-5.jpg", "/assets/img/mascots/layer-9.jpg", "/assets/img/mascots/layer-10.jpg"],
    testimonial: { quote: 'They did great at designing my logo. I wouldn\'t have gone with anyone else!', name: "Ryan", company: "Big Country Heat & Air" },
    deliverables: ["Logo design", "Mascot illustration", "Business cards", "Collateral design"],
    external: "https://je.design/projects/macdavy-heating-and-air",
  },
  {
    slug: "graybeard-construction",
    services: ["brand-identity", "company-apparel"],
    title: "Graybeard Construction",
    category: "Brand Identity",
    industry: "Construction",
    cat: "construction",
    img: "/assets/img/work/graybeard.jpg",
    blurb: "Experience is in the name — a rugged, character-driven identity carried across jerseys, trucks and job-site signage.",
    gallery: ["/assets/img/work/graybeard.jpg", "/assets/img/work/bison-roofing.jpg", "/assets/img/work/big-spring.jpg", "/assets/img/mascots/layer-16.jpg", "/assets/img/revenue/rev-3.jpg", "/assets/img/revenue/rev-4.jpg", "/assets/img/mascots/layer-14.jpg", "/assets/img/work/salty-soft-wash.jpg"],
    testimonial: { quote: 'These guys are top notch!! I have had many designers in the past that do not even come close to what these guys put out.', name: "Paul Margott", company: "Window Blasters" },
    deliverables: ["Logo design", "Mascot illustration", "Company apparel", "Five-page style guide"],
    external: "https://je.design/projects/graybeard-construction-and-maintenance-brand-identity",
  },
  {
    slug: "bison-roofing",
    services: ["brand-identity", "print-collateral"],
    title: "Bison Roofing & Construction",
    category: "Brand Identity",
    industry: "Construction",
    cat: "construction",
    img: "/assets/img/work/bison-roofing.jpg",
    blurb: "A heavyweight mark for a roofing crew — strength you can read from the street, applied from helmets to estimates.",
    gallery: ["/assets/img/work/bison-roofing.jpg", "/assets/img/work/graybeard.jpg", "/assets/img/work/big-spring.jpg", "/assets/img/mascots/layer-16.jpg", "/assets/img/revenue/rev-3.jpg", "/assets/img/revenue/rev-4.jpg", "/assets/img/mascots/layer-14.jpg", "/assets/img/work/salty-soft-wash.jpg"],
    testimonial: { quote: 'The results were absolutely incredible! The designs exceeded my expectations in every way.', name: "Shevan Rowland", company: "Lakeview Roofing LLC" },
    deliverables: ["Logo design", "Five-page style guide", "Print collateral", "Yard signs"],
    external: "https://je.design/projects/bison-roofing-and-construction",
  },
  {
    slug: "big-spring-builders",
    services: ["brand-identity", "vehicle-wraps", "print-collateral"],
    title: "Big Spring Builders, Co.",
    category: "Brand Identity",
    industry: "Construction",
    cat: "construction",
    img: "/assets/img/work/big-spring.jpg",
    blurb: "A classic, established feel for a builder that plays the long game — identity, fleet graphics and collateral in one cohesive system.",
    gallery: ["/assets/img/work/big-spring.jpg", "/assets/img/work/graybeard.jpg", "/assets/img/work/bison-roofing.jpg", "/assets/img/mascots/layer-16.jpg", "/assets/img/revenue/rev-3.jpg", "/assets/img/revenue/rev-4.jpg", "/assets/img/mascots/layer-14.jpg", "/assets/img/work/salty-soft-wash.jpg"],
    testimonial: { quote: 'Very professional, very quick to respond — and the logo turned out AMAZING!', name: "Ezri Valdes", company: "TrashPanda" },
    deliverables: ["Logo design", "Vehicle graphics", "Five-page style guide", "Collateral design"],
    external: "https://je.design/projects/big-spring-builders-co-brand-identity",
  },
  {
    slug: "jump-party",
    services: ["brand-identity", "company-apparel"],
    title: "Jump Party!",
    category: "Brand Identity",
    industry: "Party / Entertainment",
    cat: "entertainment",
    img: "/assets/img/work/jump-party.jpg",
    blurb: "Pure bottled fun — a high-energy identity for a party rental company, built to make kids point and parents remember.",
    gallery: ["/assets/img/work/jump-party.jpg", "/assets/img/mascots/layer-7.jpg", "/assets/img/mascots/layer-19.jpg", "/assets/img/work/boss-hawgs.jpg", "/assets/img/mascots/layer-21.jpg", "/assets/img/work/stoopid-energy.jpg", "/assets/img/mascots/layer-11.jpg", "/assets/img/mascots/layer-13.jpg"],
    testimonial: { quote: 'Quick turnaround & very professional. I give the team a 10/10.', name: "Julio Santiago", company: "August Hardscapes" },
    deliverables: ["Logo design", "Mascot illustration", "Company apparel", "Five-page style guide"],
    external: "https://je.design/projects/jump-party-brand-identity",
  },
  {
    slug: "zero-gravity-atv",
    services: ["websites"],
    title: "Zero Gravity ATV Rental",
    category: "Website Design",
    industry: "Recreation",
    cat: "web",
    img: "/assets/img/work/zero-gravity.jpg",
    blurb: "An adrenaline-first website for an ATV rental outfit — built to get visitors from landing page to booked ride in as few clicks as possible.",
    gallery: ["/assets/img/work/zero-gravity.jpg", "/assets/img/work/bags-website.jpg", "/assets/img/work/zero-gravity.jpg", "/assets/img/work/bags-website.jpg", "/assets/img/revenue/rev-6.jpg", "/assets/img/revenue/rev-8.jpg", "/assets/img/work/zero-gravity.jpg", "/assets/img/work/bags-website.jpg"],
    testimonial: { quote: 'I could not have asked for a better experience. Working with Jeremy was an insane value!', name: "Nick Boyles", company: "Breeze Painting" },
    deliverables: ["Website design", "Development", "Booking flow", "Content layout"],
    external: null,
  },
  {
    slug: "bags",
    services: ["websites"],
    title: "Bags",
    category: "Website Design",
    industry: "Fashion / eCommerce",
    cat: "web",
    img: "/assets/img/work/bags-website.jpg",
    blurb: "A clean, conversion-focused storefront for a fashion brand — product-first layouts that let the merchandise do the talking.",
    gallery: ["/assets/img/work/bags-website.jpg", "/assets/img/work/zero-gravity.jpg", "/assets/img/work/zero-gravity.jpg", "/assets/img/work/bags-website.jpg", "/assets/img/revenue/rev-6.jpg", "/assets/img/revenue/rev-8.jpg", "/assets/img/work/zero-gravity.jpg", "/assets/img/work/bags-website.jpg"],
    testimonial: { quote: 'They did great at designing my logo. I wouldn\'t have gone with anyone else!', name: "Ryan", company: "Big Country Heat & Air" },
    deliverables: ["Website design", "Development", "eCommerce layout", "Brand application"],
    external: null,
  },
];

export function getProject(slug) {
  return projects.find((p) => p.slug === slug);
}
