// Real client reviews (Google & Facebook) — shared across pages
export const reviews = [
  { name: "Shevan Rowland", company: "Lakeview Roofing LLC",
    short: "I recently had the pleasure of working with this company for a logo design, t-shirt design, yard sign design, and several other projects. The results were absolutely incredible! The designs exceeded my expectations in every way.",
    full: "I recently had the pleasure of working with this company for a logo design, t-shirt design, yard sign design, and several other projects. The results were absolutely incredible! The designs exceeded my expectations in every way. Communication was seamless throughout the entire process, and the delivery was outstanding. Highly recommend their services!" },
  { name: "Ryan", company: "Big Country Heat & Air",
    short: "They did great at designing my logo. I wouldn't have gone with anyone else!",
    full: "They did great at designing my logo. I wouldn't have gone with anyone else!" },
  { name: "Paul Margott", company: "Window Blasters",
    short: "These guys are top notch!! I have had many designers in the past that do not even come close to what these guys put out. I am extremely happy with the design of my logo and I know for sure it is going to grab attention.",
    full: "These guys are top notch!! Seriously, I have had many designers in the past that do not even come close to what these guys put out. I am extremely happy with the design of my logo and I know for sure without a doubt it is going to grab attention. I am so happy in fact that I am having them do any and all design work my company has going forward including shirts and business cards which are in the process. Well worth paying the money for something such as the face of your company." },
  { name: "Ezri Valdes", company: "TrashPanda",
    short: "I 100% recommend working with Jeremy and his team. He is very professional, very quick to respond and the logo he did for my small business turned out AMAZING!",
    full: "I 100% recommend working with Jeremy and his team. He is very professional, very quick to respond and the logo he did for my small business turned out AMAZING! His work is well worth the money and I for sure will be using his services again in the future!" },
  { name: "Julio Santiago", company: "August Hardscapes",
    short: "My experience with the Jeremy Ellsworth team was phenomenal. They brought my existing logo to life with some beautiful colors that really help my brand pop. Quick turnaround & very professional. I give the team a 10/10.",
    full: "My experience with the Jeremy Ellsworth team was phenomenal. They brought my existing logo to life with some beautiful colors that really help my brand pop. Quick turnaround & very professional. Super on point with the few versions of logos they showed me and they were quick to finish everything up & provide me the final files. I give the team a 10/10. Would absolutely use again and highly recommend you guys to use them to keep your brand cohesive throughout." },
  { name: "Nick Boyles", company: "Breeze Painting",
    short: "Their communication was excellent — I was constantly informed and updated on the process and timeline. Not to mention the quality of our new logo is incredible. Working with Jeremy was an insane value!",
    full: "I had a fantastic experience working with Jeremy and the team on a new logo for my business. Their communication was excellent, I was constantly informed and updated on the process and timeline. I could not have asked for a better experience. Not to mention the quality of our new logo is incredible. Working with Jeremy was an insane value!" },
];
