// Services data — CMS-ready, same pattern as projects.js
export const services = [
  {
    slug: "brand-identity",
    note: "If you only invest in one thing, make it this — everything else we make is built on top of it.",
    industries: "HVAC · Electrical · Plumbing · Roofing · Painting · Startups",
    num: "01",
    title: "Logo & Branding",
    desc: "The cornerstone of everything. We research your market, sketch by hand and build an original logo system with a five-page style guide — so every future application stays consistent, from business cards to billboards.",
    bullets: ["Logo design", "Five-page style guide", "Color & type system", "Usage rules"],
    img: "/assets/img/work/boss-hawgs.jpg",
  },
  {
    slug: "vehicle-wraps",
    note: "One wrapped truck can out-advertise a billboard — and yours is parked in the customer's neighborhood.",
    industries: "Service trucks · Vans · Trailers · Fleets",
    num: "02",
    title: "Vehicle Wrap",
    desc: "Your trucks are billboards that drive themselves. We design wraps that read instantly at 40mph — bold, legible and impossible to ignore — turning every job site and stoplight into an impression.",
    bullets: ["Full & partial wrap design", "Fleet consistency", "Print-ready files", "Installer coordination"],
    img: "/assets/img/work/salty-soft-wash.jpg",
  },
  {
    slug: "websites",
    short: "Website",
    note: "Designed to match your brand exactly — not a theme that looks like everyone else's.",
    industries: "Home service · Rentals · eCommerce · Local business",
    num: "03",
    title: "Website Design & Dev.",
    desc: "A strategic website that captures your identity and converts visitors into customers. Designed and developed in-house to match your brand exactly — fast, modern and built to grow with you.",
    bullets: ["Design & development", "Mobile-first build", "Conversion-focused layout", "Launch support"],
    img: "/assets/img/work/zero-gravity.jpg",
  },
  {
    slug: "print-collateral",
    note: "Everything arrives print-ready in AI, SVG and PDF — your printer will thank you.",
    industries: "Business cards · Brochures · Menus · Yard signs",
    num: "04",
    title: "Print Collateral",
    desc: "Business cards, brochures, menus, yard signs — the physical touchpoints that make a small business feel established. Print-crisp files in every format your printer could ask for.",
    bullets: ["Business cards", "Brochures & menus", "Yard signs", "Trade collateral"],
    img: "/assets/img/work/macdavy.jpg",
  },
  {
    slug: "packaging-labels",
    short: "Package / Labels",
    note: "We design for the shelf and the photo feed — both matter now.",
    industries: "Beverage · Food · Retail products",
    num: "05",
    title: "Packaging & Labels",
    desc: "Shelf-ready product design that makes customers reach for yours first. From cans to boxes to label systems — designed to pop in a lineup and photograph beautifully.",
    bullets: ["Label design", "Package design", "Dieline-ready files", "Mockups"],
    img: "/assets/img/work/stoopid-energy.jpg",
  },
  {
    slug: "company-apparel",
    note: "When the crew looks pro, customers assume the work is too.",
    industries: "Crews · Uniforms · Trade shows · Merch",
    num: "06",
    title: "Company Apparel",
    desc: "Shirts and uniforms your crew will actually want to wear. Apparel that turns your team into walking proof that your company has its act together.",
    bullets: ["Shirt & uniform design", "Mascot applications", "Print-ready artwork", "Vendor-ready files"],
    img: "/assets/img/work/graybeard.jpg",
  },
];
